import { CardImage, YugiohCard } from "@/types/Yugioh";
import { trpc } from "@/utils/trpc";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [yugiCard, setYugiCard] = useState<CardImage>();
  const [fetchCard, setFetchCard] = useState(false);
  const newCard = trpc.useQuery(["getCard", { resp: "wheres the money" }], {
    enabled: false,
  });

  console.log("newCard:", newCard);

  const getNewCard = async () => {
    setFetchCard(true);
    const test = await newCard.refetch();
    if (test.data) {
      setFetchCard(false);
    }
  };
  return (
    <div className="w-screeen h-screen flex flex-col gap-y-5 items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {fetchCard ? (
        <div
          className={`w-[422px] h-[617px] bg-[#bebebedd] animate-pulse animate-ping`}
        />
      ) : (
        <img
          src={newCard.data?.cardImage.image_url}
          alt=""
          className="w-[422px] h-[617px]"
        />
      )}

      <button
        className="w-[200px] h-[100px] bg-blue-300 rounded-lg"
        onClick={() => getNewCard()}
      >
        random card
      </button>
    </div>
  );
};

export default Home;
